language: generic
sudo: required
services: docker
matrix:
  include:
    # https://hub.docker.com/_/fedora/
    - env: CONTAINER_IMAGE=fedora:29 TOXENV=lint-py3,lint-py2,py36,py27
    - env: CONTAINER_IMAGE=fedora:28 TOXENV=py35,py26
    - env: CONTAINER_IMAGE=fedora:27 TOXENV=py36
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py37,py27
    # https://hub.docker.com/r/junaruga/rpm-py-installer-docker/
    - env: CONTAINER_IMAGE=junaruga/rpm-py-installer-docker:26 TOXENV=intg
    # https://hub.docker.com/_/centos/
    - env: CONTAINER_IMAGE=centos:7 TOXENV=py34,py27
    - env: CONTAINER_IMAGE=centos:6 TOXENV=py27,py26
    # https://hub.docker.com/_/ubuntu/
    - env: CONTAINER_IMAGE=ubuntu:bionic TOXENV=py36,py27
    - env: CONTAINER_IMAGE=ubuntu:trusty TOXENV=py34,py27
  allow_failures:
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py37,py27
  fast_finish: true
install:
  - |
    if [ "${CONTAINER_IMAGE}" = "" ]; then
        echo "Container image not defined." 1>&2
        exit 1
    fi
  - |
    DOCKER_FILE=.travis/Dockerfile
    if [ "${CONTAINER_IMAGE}" = "centos:6"  ]; then
        DOCKER_FILE=.travis/Dockerfile.centos6
    elif [[ "${CONTAINER_IMAGE}" =~ centos ]]; then
        DOCKER_FILE=.travis/Dockerfile.centos
    elif [ "${CONTAINER_IMAGE}" = "ubuntu:bionic" ]; then
        DOCKER_FILE=.travis/Dockerfile.ubuntu.bionic
    elif [[ "${CONTAINER_IMAGE}" =~ ubuntu ]]; then
        DOCKER_FILE=.travis/Dockerfile.ubuntu
    fi
    export DOCKER_FILE
  - |
    sed -i "/^FROM / s|FROM .*|FROM ${CONTAINER_IMAGE}|" "${DOCKER_FILE}"
  - |
    travis_retry docker build \
        --rm \
        -t rpm-py-installer \
        -f "${DOCKER_FILE}" \
        --build-arg TOXENV="${TOXENV}" \
        .
script:
  - |
    docker run \
        --rm \
        -e TOXENV="${TOXENV}" \
        -t \
        rpm-py-installer
branches:
  only:
    - master
