language: generic
sudo: required
services: docker
matrix:
  include:
    # https://hub.docker.com/_/fedora/
    - env: CONTAINER_IMAGE=fedora:26 TOXENV=lint-py3,lint-py2,py36,py35,py27
    - env: CONTAINER_IMAGE=fedora:25 TOXENV=py36
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py36,py27
    # https://hub.docker.com/r/junaruga/rpm-py-installer-docker/
    - env: CONTAINER_IMAGE=junaruga/rpm-py-installer-docker:26 TOXENV=intg
    # https://hub.docker.com/_/centos/
    - env: CONTAINER_IMAGE=centos:7 TOXENV=py34,py27
  allow_failures:
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py36,py27
    - language: python
      python: nightly
  fast_finish: true
install:
  - |
    if [ "${CONTAINER_IMAGE}" = "" ]; then
        echo "Container image not defined." 1>&2
        exit 1
    fi
  - |
    DOCKER_FILE=.travis/Dockerfile
    if [[ "${CONTAINER_IMAGE}" =~ centos ]]; then
        DOCKER_FILE=.travis/Dockerfile.centos
    fi
    export DOCKER_FILE
  - |
    sed -i "/^FROM / s|FROM .*|FROM ${CONTAINER_IMAGE}|" "${DOCKER_FILE}"
  - |
    docker build \
        -t rpm-py-installer \
        -f "${DOCKER_FILE}" \
        .
script:
  - |
    docker run \
        -e TOXENV="${TOXENV}" \
        -t \
        rpm-py-installer

branches:
  only:
    - master
